- hosts: hyperv
  tasks:
    - name: Create a VM
      import_role:
        name: hyperv
      vars:
        vmstate: started
        vmname: DC1
        vm_os: 'Windows2022'
        # vmgeneration: 2
        # vmcpu: 2
        # vmmemory: 2048MB