- hosts: hyperv
  tasks:
    - name: Create a VM
      import_role:
        name: hyperv
      vars:
        vmstate: absent
        vmname: dc1
        # vmgeneration: 2
        # vmcpu: 2
        # vmmemory: 1024MB