- hosts: hyperv
  tasks:
    - name: Create a VM
      import_role:
        name: hyperv
      vars:
        vmstate: present
        vmname: dc2
        vmgeneration: 2
        vmcpu: 2
        vmmemory: 1024MB