---
# handlers file for hyperv
- name: PowerOnVm
  when: vm_state == 'started'
  win_hyperv_guest:
    name: "{{ vm_name }}"
    state: started
    
- name: Remove Vm Directory
  win_file:
    path: "{{ vmpath }}\\{{ vm_name }}"
    state: absent