---
- name: Prepare Disk
  include: copy_windisk.yml
  when:
    - vm_os == 'Windows2022'

- name: Create Gen1 Machine
  include: create_gen1_vm.yml
  when:
    - vm_generation == 1
    - vm_state == 'present' or 'started'

- name: Create Gen2 Machine
  include: create_gen2_vm.yml
  when: 
    - vm_generation == 2
    - vm_state == 'present' or 'started'

- name: Setting CPU as needed
  include: set_cpu.yml
  when: 
    - vm_state != 'absent'

- name: Power on as needed
  include: poweron_vm.yml
  when: vm_state == 'started'

- name: Destroy as needed
  include: delete_vm.yml
  when: vm_state == 'absent'